name: LocProofApp
options:
  bundleIdPrefix: com.locproof
targets:
  LocProofApp:
    type: application
    bundleId: com.locproof.LocProofApp
    platform: iOS
    deploymentTarget: "16.0"
    sources: [LocProofApp]
    info:
      path: LocProofApp/Info.plist
      properties:
        UILaunchScreen: {}
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations: {}
    dependencies:
      - target: LocProofTunnel
  LocProofTunnel:
    type: app-extension
    bundleId: com.locproof.LocProofApp.LocProofTunnel
    platform: iOS
    deploymentTarget: "16.0"
    sources: [LocProofTunnel]
    info:
      path: LocProofTunnel/Info.plist
    settings:
      EXCLUDED_ARCHS: ""
